### ISSUE TITLE
Folder structure query

### ISSUE THREAD

**Issue by DGRamya** [cloudmesh-community/hid-sp18-406#2]
@laszewsk,
Professor, Should I remove the "flaskConnexion" folder from the swagger assignment folder? Docker assignment is present inside the "docker" folder. Could you please review and guide me.

**Comment by laszewsk** [comment]
your assignment is not complete, makefile missing,  once corrected place files you wrote according to assignment and delete flaskConetion

see handbook assignments section

**Comment by DGRamya** [comment]
@laszewsk,
I updated the folder structure accordingly. Thank you.
